### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mabruzzo** [mabruzzo/pyvsf#1]
This just exists to track a list of ideas that might be worth pursuing in the future. This should mostly be thought of as a wishlist (except for stuff that we explicitly list as requirements for a version 1.0 release).

### Convenience
- [ ] `vsf_props`: add built-in support where the vector values have fewer dimensions than the positions. 
   - Users can currently perform these types of calculations by setting the unused component(s) of the vector value at all locations to a constant value (e.g. if you have a 1D velocity field, the user could just set `velocity_y = velocity_z = 0` at all points) 
- [ ] `vsf_props` & `twopoint_correlation`: add built-in support where the position has fewer than 3 dimensions 
  - Users can currently perform these types of calculations by setting the unused component(s) of the position at all locations to a constant value (e.g. if all points only have 2D positions, the user could just set `z = 0` at all points)
- [ ] `vsf_props` & `twopoint_correlation`: it would be nice if stat_kw_pairs could just accept the string specifying a statistic name for all statistics (i.e. most of them) that don't require kwargs.
 
### Ideas For New Features
- [ ] `vsf_props` & `twopoint_correlation`: To more fully support applications where the user is using this module to compute quantities from images, it could be useful to support a different distance "metric" to more correctly compute distances on the sky.
  - I started to prototype this once. The plan would be to use the special case of the Vincenty formula (described on this [wikipedia page](https://en.wikipedia.org/wiki/Great-circle_distance#Computational_formulae)).
  - I shelved this feature (it is easy to implement, a little tricky to test), until somebody indicates a need for it. This only makes a big difference from Euclidean distances when you have large scale images (e.g. HVC observations) and/or the positions are far from the "equator" of the coordinate system
- [ ] `twopoint_correlation`: it would be nice if I could ensure it works with the histogram statistic.
- [ ] `vsf_props`: it would be nice if I could add support for weighted 2nd-order velocity structure functions
- [ ]  `vsf_props` & `twopoint_correlation`: we could add an "extrema" statistic. I don't actually think this is necessary, but it might be nice for the sake of completeness (and it might help us nicely illustrate the idea of a statistic).
- [ ]  `vsf_props` (& to a lesser-extent, `twopoint_correlation`): currently we refer to the canonical structure functions as "mean" and "variance." But maybe we should alias these names with something like `"moment-1"`, `"moment-2"`, since they respectively refer to the 1st and 2nd moments about the mean (aka the 1st and 2nd [central moments](https://en.wikipedia.org/wiki/Central_moment).
  - This will become important when we consider higher order structure moments. The 3rd and 4th order structure functions are the correspond to the 3rd and 4th central moment. Whereas the 1st and 2nd central moments are exactly the mean and variance, the 3rd and 4th central moments are NOT exactly the same as skewness and kurtosis (in reality they are closely related, and we would probably use algorithms for skewness & kurtosis to help out) 

### Internal Refactoring
- [ ] It probably makes sense to refactor the python statistic kernels to actually be used as classes. I think I would also like to move away from the term kernel. When they were originally implemented, they were made into classes to effectively acts as name-spaced collections of functions. But, it has become apparent that actually storing the configuration of a statistic in an object (rather than repeatedly passing the configuration to a class method), would be more optimal.
- [ ] it would be great if the primary c++ function (currently called `calc_vsf_props` was directly passed the accumulators object(s) rather than the pairs of names and kwargs needed to construct them).
  - a lot of the functionality already exists to do this, but we would need to make some firm decisions about compound-calculations
- [ ] there is a fair amount of duplicated code between the C++ Accumulator classes. By leveraging templates, we coul

### Nice-to-have Documentation Improvements
- [ ] I think it might be more useful if a reframe some of the discussion of `vsf_props` & `twopoint_correlation` functions so that it uses the sphinx_tabs package. It might be a nice way to make some of the discussion seem a little more concrete (and less abstract) without duplicating the discussion.

### Testing
- [ ] We really need to automate the main tests with pytest (shouldn't be hard at all!)
- [ ] I want some kind of test of the weighted statistics. The easiest way to do this might be to add a C++ function intended for testing purposes that simply invokes the accumulators for an arbitrary sequence of input values.

### Misc.
- [ ] I want to setup some kind of continuous integration that runs the test suite
- [ ] I also want setup pre-commit.ci continuous integration to apply formatting.

### Prior to the 1.0 Release
- [ ] Prior to the 1.0 Release, I should remove the `small_dist_sf_props` function, which is not currently a part of the main public API. I am planning to move this function and its associated functionality to a separate branch. While this function has been **very** useful for my own research, it is very specialized, introduces a number of dependencies, and would take a lot to adequately document.
- [ ] We should probably document the "histogram" statistic (and explain how it relates to the other statistics)
- [ ] We should document how to use `vsf_props` & `twopoint_correlation` inside of a distributed calculation (e.g. MPI) OR we should revise the way in which we currently reference this idea in the documentation.
